### ISSUE TITLE
Problema ao tentar inserir um novo orçamento

### ISSUE THREAD

**Issue by wescleymatos** [Coderockr/orcamentos#100]
Ao tentar inserir um novo orçamento sem inserir nenhum valor para o campo comissão, obtive a seguinte mensagem:

> An exception occurred while executing 'INSERT INTO Quote (dueDate, taxes, version, status, profit, commission, privateNotes, deadline, priceDescription, paymentType, created, updated, project_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["2017-06-30 11:03:41", "15", "1", "1", "10", "", "", "6 meses.", "", "Parcela \u00fanica a vista.", "2017-06-17 11:03:41", null, 2]: SQLSTATE[01000]: Warning: 1265 Data truncated for column 'commission' at row 1

**Comment by wescleymatos** [comment]
O mesmo problema foi percebido para o campo "Maegem de lucro".

**Comment by eminetto** [comment]
@wescleymatos acho que esta issue foi corrigida com o PR que vc mandou, certo?

**Comment by wescleymatos** [comment]
Correto.
