### ISSUE TITLE
Problema ao gerar orçamento

### ISSUE THREAD

**Issue by fredroo** [Coderockr/orcamentos#86]
Fatal error: Call to undefined function Orcamentos\Controller\datefmt_create() in D:\Desenvolvimento\xampp\htdocs\orcamentos\src\Orcamentos\Controller\QuoteController.php on line 255

Alguém já teve esse problema?

**Comment by eminetto** [comment]
Adicionei o comentário no README do projeto avisando que é preciso a extensão intl
