### ISSUE TITLE
Total de Horas

### ISSUE THREAD

**Issue by goldblade** [Coderockr/orcamentos#92]
Olá Elton,

Utilizo seu sistema de orçamentos e desde já agradeço por sua disponibilização. A minha dúvida é só uma questão de negócio, e gostaria de compartilhar, como é feito o cálculo total(estimado de horas) para digamos por exemplo: Programador WEB(40 horas) no projeto. Eu utilizo uma planilha e faço uma estimativa do tempo que levo para fazer "CRUD de tal funcionalidade", não é bem um calculo por pontos de função, mas é a forma que tenho trabalhado. Depois disso eu coloco essas horas no sistema de orçamentos. A idéia é saber se os demais também utilizam assim e se for "maioria". Tava pensando em adicionar essa funcionalidade no seu sistema de orçamentos.

**Comment by eminetto** [comment]
Opa, blz?

Legal que o projeto está sendo útil para mais alguém :)

Acho que não entendi muito bem a sua dúvida. Mas o que eu faço é colocar o número de horas de cada profissional e o sistema calcula o total de horas e o valor, baseado no valor de cada hora da pessoa
Você pode dar mais detalhes da sua dúvida?

**Comment by goldblade** [comment]
Opa Elton, 




Vamos lá deixa ver se consigo ser mais claro.




A questão é como você chega ao numero de horas de cada profissinal antes. Eu presumo que você tenha uma base de quantas horas leva para desenvolver o projeto. Exemplo: projeto Site da lanchonete - Tempo estimado total: 120 horas de desenvolvimento, se você possui 2 programadores, ficaria 60 horas de cada. E ai claro o sistema se encarrega de calcular o valor de cada hora de cada programador + taxas + comissões + lucros e etc, e te dar um valor total do projeto. 




A dúvida consiste na definição que o projeto Site da Lanchonete - vai levar a estimativa de 120 horas de programação para ficar pronto. 




Como minha empresa no momento, só conta como programador e “faz tudo da estrela” somente minha única pessoa. Eu calculo o total de horas do projeto, utilizando uma planilha de requisitos levantados e aprovadas pelo o cliente, e uma estimativa de horas que levo para desenvolver cada funcionalidade. 




A minha idéia de nova funcionalidade no sistema de orçamentos, seria a criação do cadastro de requisitos do projeto e o tempo extimado para realização dos mesmos. Onde já me daria o total de horas estimado que o projeto vai precisar. Facilitando a minha vida na hora de inserir a quantidade de horas do programador, evitando a necessidade de ter um arquivo de planilha de requisitos para cada projeto.




Por isso o questionamento de como os demais trabalham em relação a isso.  Para que possa fazer essa nova funcionalidade meio que “universal” e não somente para resolver o meu “problema”.  




Atenciosamente, 




Eduardo Júnior

Irecê - Bahia
















 





—

**Comment by eminetto** [comment]
Opa
Me parece uma ideia legal. O que eu faço é parecido com isso mesmo. Eu levanto os pontos, anoto num documento a estimativa, discuto com a equipe e depois cadastro no sistema só o somatório de horas de cada envolvido para gerar o valor final da proposta.
Acho que seria uma funcionalidade interessante, até para ter um histórico dos projetos e no futuro gerar isso mais automaticamente ainda. 
Se você iniciar o desenvolvimento acho que mais gente ajudaria :)

**Comment by goldblade** [comment]
Ok, vou criar um branch no fork do projeto, depois que codificar algo e testar, te mando um pull request para avaliação :)
