### ISSUE TITLE
DialogHelper not found

### ISSUE THREAD

**Issue by maiconpinto** [Coderockr/orcamentos#95]
Fiz clone, e composer update. 

Executei `./bin/orcamentos orcamentos:initialize` e apresentou este erro:

**PHP Fatal error:  Class 'Symfony\Component\Console\Helper\DialogHelper' not found in /var/www/html/orcamentos/cli-config.php on line 53**

Eu preciso instalar alguma coisa na minha máquina? Editar algum arquivo?

Obrigado!

**Comment by maiconpinto** [comment]
Eu não sei se está correto, mas acabei comentando as linhas 53-55.

```php
//new DialogHelper(),
//new ProgressHelper(),
//new TableHelper(),
```

E executei novamente, o `./bin/orcamentos orcamentos:initialize`. Aí apareceu um setup, digitei meus dados. Após apareceu a tela com login e senha. Digitei os dados, *Entrar*, mas então **404 Not Found**. :(

**Comment by eminetto** [comment]
O DialogHelper foi descontinuado no Symfony 3. Como não o composer.lock havia sido removido do repositório ao fazer o composer install era instalada a última versão. Commitei o composer.json e o composer.lock corretos e agora deve funcionar
